### PR TITLE
 Added clarification for version of djangocms-cascade

### PR DESCRIPTION
**Pull request by execut**
[//]: # (Thank you for helping us out: your efforts mean great deal to the project and the community as a whole!)

[//]: # (Before you proceed:)

[//]: # (1. Make sure to add yourself to `CONTRIBUTORS.rst` through this PR provided you're contributing here for the first time)
[//]: # (2. Don't forget to update the `docs/` presuming others would benefit from a concise description of whatever that you're proposing)

## Description

Fixed bugs #41 and #43 with versions conflict of djangocms-cascade

[//]: # (What's it you're proposing?)

## Rationale

[//]: # (Why does the project need that?)

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

### CODE REVIEW

**Comment by jhonvidal** [comment]
thanks

**Comment by jhonvidal** [comment]
It keeps reporting the same error, I have followed the steps to the letter.

Mi file pipfile:

[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
Django = ">=3"
django-allauth = "*"
django-angular = ">=2.3"
django-filer = "*"
django-ipware = "*"
django-sass-processor = "*"
django-select2 = "*"
django-filter = "*"
django-parler = "*"
django-parler-rest = "*"
djangorestframework = "*"
django-rest-auth = "*"
django-polymorphic = ">=2.1"
django-admin-sortable2 = "*"
django-fsm = "*"
django-fsm-admin = "*"
django-phonenumber-field = "*"
django-post_office = "*"
phonenumbers = "*"
django-cms = ">=3.7.2"
djangocms-bootstrap = "*"
djangocms-cascade = ">=1.3.1"
djangocms-text-ckeditor = ">=3.9.1"
libsass = "*"
django-shop = ">=1.2.1,<2"


[dev-packages]
tox = "*"
pytest = "*"
pytest-django = "*"
beautifulsoup4 = "*"
lxml = "*"
factory-boy = "*"
pytest-factoryboy = "*"

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true`
`


the error when installing with pipenv:

`
There are incompatible versions in the resolved dependencies:
  django>=3 (from -r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 8))
  django<3.1,>=2.1 (from django-shop==1.2.4->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 26))
  django<3.3,>=1.8 (from django-admin-sortable2==1.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 14))
  django<4.0,>=2.2 (from django-filer==2.1rc3->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 17))
  django>=1.6 (from django-fsm-admin==1.2.4->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 25))
  django>=1.8.0 (from django-rest-auth==0.9.5->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 19))
  django>=2.0 (from django-allauth==0.45.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 21))
  django>=2.1 (from django-angular==2.3->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 23))
  django>=2.1 (from django-polymorphic==3.0.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 9))
  django>=2.2 (from django-cms==3.9.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 4))
  django>=2.2 (from django-filter==2.4.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 15))
  django>=2.2 (from django-phonenumber-field==5.2.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 22))
  django>=2.2 (from django-post-office==3.5.3->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 7))
  django>=2.2 (from django-select2==7.7.1->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 16))
  django>=2.2 (from djangorestframework==3.12.4->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 6))
  django>=3.1 (from djangocms-cascade==2.1->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 11))

`

**Comment by jhonvidal** [comment]
It keeps reporting the same error, I have followed the steps to the letter.

Mi file pipfile:

> [[source]]
> url = "https://pypi.python.org/simple"
> verify_ssl = true
> name = "pypi"
> 
> [packages]
> Django = ">=3"
> django-allauth = ""
> django-angular = ">=2.3"
> django-filer = ""
> django-ipware = ""
> django-sass-processor = ""
> django-select2 = ""
> django-filter = ""
> django-parler = ""
> django-parler-rest = ""
> djangorestframework = ""
> django-rest-auth = ""
> django-polymorphic = ">=2.1"
> django-admin-sortable2 = ""
> django-fsm = ""
> django-fsm-admin = ""
> django-phonenumber-field = ""
> django-post_office = ""
> phonenumbers = ""
> django-cms = ">=3.7.2"
> djangocms-bootstrap = ""
> djangocms-cascade = ">=1.3.1"
> djangocms-text-ckeditor = ">=3.9.1"
> libsass = ""
> django-shop = ">=1.2.1,<2"
> 
> [dev-packages]
> tox = ""
> pytest = ""
> pytest-django = ""
> beautifulsoup4 = ""
> lxml = ""
> factory-boy = ""
> pytest-factoryboy = "*"
> 
> [requires]
> python_version = "3.7"
> 
> [pipenv]
> allow_prereleases = true

the error when installing with pipenv:



> There are incompatible versions in the resolved dependencies:
> django>=3 (from -r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 8))
> django<3.1,>=2.1 (from django-shop==1.2.4->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 26))
> django<3.3,>=1.8 (from django-admin-sortable2==1.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 14))
> django<4.0,>=2.2 (from django-filer==2.1rc3->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 17))
> django>=1.6 (from django-fsm-admin==1.2.4->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 25))
> django>=1.8.0 (from django-rest-auth==0.9.5->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 19))
> django>=2.0 (from django-allauth==0.45.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 21))
> django>=2.1 (from django-angular==2.3->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 23))
> django>=2.1 (from django-polymorphic==3.0.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 9))
> django>=2.2 (from django-cms==3.9.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 4))
> django>=2.2 (from django-filter==2.4.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 15))
> django>=2.2 (from django-phonenumber-field==5.2.0->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 22))
> django>=2.2 (from django-post-office==3.5.3->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 7))
> django>=2.2 (from django-select2==7.7.1->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 16))
> django>=2.2 (from djangorestframework==3.12.4->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 6))
> django>=3.1 (from djangocms-cascade==2.1->-r /tmp/pipenvs57yibf4requirements/pipenv-9d9g4pxe-constraints.txt (line 11))
>

**Comment by execut** [comment]
oops, I seem to be mistaken in the package. I made a new request #48

**Comment by jhonvidal** [comment]
> oops, I seem to be mistaken in the package, sorry. I made a new request #48


Thank you very much, the installation was a success, but I have a problem, it is the following:

When I run 

> manage.py runserver

and I go to the product list or when I try to add a new product, I always get this same error:


> ValueError at /en/catalog/
> Can not add/substract money in different currencies.
> Request Method:	GET
> Request URL:	http://localhost:8000/en/catalog/
> Django Version:	3.0.14
> Exception Type:	ValueError
> Exception Value:	
> Can not add/substract money in different currencies.
> Exception Location:	/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/shop/money/money_maker.py in _assert_addable, line 220
> Python Executable:	/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/bin/python
> Python Version:	3.7.11
> Python Path:	
> ['/home/docko/Desarrollo/implementacion/shopexample/shoponline',
>  '/usr/lib/python37.zip',
>  '/usr/lib/python3.7',
>  '/usr/lib/python3.7/lib-dynload',
>  '/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages']
> Server time:	Mon, 12 Jul 2021 18:12:30 +0000
> 


TRACEBACK:


> [2021-07-12 18:12:30,940 log] ERROR: Internal Server Error: /en/catalog/
> Traceback (most recent call last):
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/cms/utils/decorators.py", line 19, in inner
>     return func(request, *args, **kwargs)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
>     return view_func(*args, **kwargs)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
>     response = self.handle_exception(exc)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
>     raise exc
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/shop/views/catalog.py", line 128, in get
>     response = self.list(request, *args, **kwargs)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/mixins.py", line 43, in list
>     return self.get_paginated_response(serializer.data)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/serializers.py", line 745, in data
>     ret = super().data
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/serializers.py", line 246, in data
>     self._data = self.to_representation(self.instance)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/serializers.py", line 664, in to_representation
>     self.child.to_representation(item) for item in iterable
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
>     self.child.to_representation(item) for item in iterable
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/serializers.py", line 515, in to_representation
>     ret[field.field_name] = field.to_representation(attribute)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/rest_framework/fields.py", line 1882, in to_representation
>     return method(value)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/shop/serializers/bases.py", line 52, in get_price
>     return '{:f}'.format(price)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/shop/money/money_maker.py", line 50, in __format__
>     amount = Decimal.quantize(self, self._cents).__format__(specifier)
>   File "/usr/lib/python3.7/_pydecimal.py", line 2588, in quantize
>     if ans != self:
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/shop/money/money_maker.py", line 152, in __eq__
>     other = self._assert_addable(other)
>   File "/home/docko/.local/share/virtualenvs/shoponline-bXuYyBnv/lib/python3.7/site-packages/shop/money/money_maker.py", line 220, in _assert_addable
>     raise ValueError("Can not add/substract money in different currencies.")
> ValueError: Can not add/substract money in different currencies.
> [2021-07-12 18:12:30,948 basehttp] ERROR: "GET /en/catalog/ HTTP/1.1" 500 23918


I am using python 3.7.11 and I have also tried python 3.9 and it follows the same error.

I have already reported it a year ago and I cannot find a solution, some help please

**Comment by jhonvidal** [comment]
I have the same problem and so far I can't find a solution, if you managed to solve it please tell us how

**Pull request merged**
